stages:
  - test
  - sbom

default:
  tags:
    - flarenetwork
  artifacts:
    expire_in: 3 days

include:
  - component: gitlab.com/flarenetwork/ci-components-private/lgtm@2
  - component: gitlab.com/flarenetwork/ci-components-private/dependency-track@2
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml
  - component: gitlab.com/flarenetwork/ci-components-private/lint-dockerfile@2
  - component: gitlab.com/flarenetwork/ci-components-private/lint-go@2
    inputs:
      go_version: "1.26.8"
      golangci_version: "v2.14.0"
      golangci_config_file: ".golangci.yml"
      tags: ["flarenetwork-lg"]
  - component: gitlab.com/flarenetwork/ci-components-private/test-go@2
    inputs:
      go_version: "1.26.8"
      cobertura_go_version: "1.26.8"
      go_test_command: "go test -race -timeout 20m -covermode=atomic -coverprofile=coverage.out -coverpkg=github.com/flare-foundation/tee-node/... ./..."
      tags: ["flarenetwork-lg"]
