name: repro-container-images

on:
  push:
    branches: [ "ci" ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build-repro:
    name: Build (repro)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      with:
        fetch-depth: 0

    - name: Set build metadata
      env:
        REPOSITORY: '${{ github.repository }}'
      run: |
        echo "IMAGE_TAG=ghcr.io/${REPOSITORY,,}:ci" >>$GITHUB_ENV
        echo "SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)" >>$GITHUB_ENV

    - name: Login to ghcr.io
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0  # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Reproducibly build and push image
      uses: freedomofpress/repro-build@e3539de5c53c198f897fe6053ec2662f8f0e9bf3  # 1.1.0
      with:
        tags: ${{ env.IMAGE_TAG }}
        source_date_epoch: ${{ env.SOURCE_DATE_EPOCH }}
        push: true

  verify-repro:
    name: Verify digest (daily)
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      with:
        ref: ci
        fetch-depth: 0

    - name: Set build metadata
      env:
        REPOSITORY: '${{ github.repository }}'
      run: |
        echo "IMAGE_TAG=ghcr.io/${REPOSITORY,,}:ci" >>$GITHUB_ENV
        echo "SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)" >>$GITHUB_ENV

    - name: Login to ghcr.io
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0  # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify image reproducibility
      uses: freedomofpress/repro-build/verify@9987861aa56cdd7d75baa5dbdb7d7b6d719f1653  # 2.0.0
      with:
        target_image: ${{ env.IMAGE_TAG }}
        source_date_epoch: ${{ env.SOURCE_DATE_EPOCH }}
